services:
    db:
        image: postgres:18rc1-trixie
        restart: unless-stopped
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: main
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - 5432:5432
volumes:
    db:
